name: CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        resolver-version:
          - 'lts-12'
          - 'lts-13'
          - 'lts-14'
          - 'lts-15'
          - 'lts-16'
          - 'lts-17'
          - 'lts-18'
          - 'lts-19'
          - 'nightly'
    env:
      STACK_YAML: stack-travis.yaml
    steps:
    - uses: actions/checkout@v2
    - name: Cache .stack
      id: cache-stack
      uses: actions/cache@v1
      with:
        path: ~/.stack
        key: ${{ runner.os }}-stack-${{ matrix.resolver-version }}
        restore-keys: |
          ${{ runner.os }}-stack-
    - name: Cache .local
      id: cache-local
      uses: actions/cache@v1
      with:
        path: ~/.local
        key: ${{ runner.os }}-local-${{ matrix.resolver-version }}
        restore-keys: |
          ${{ runner.os }}-local-
    # - uses: actions/setup-haskell@v1
    #   with:
    #     ghc-version: '8.8.2'
    #     cabal-version: '3.0'
    - name: Install stack
      run: |
        mkdir -p ~/.local/bin
        export PATH=~/.local/bin:$PATH
        export RESOLVER=${{ matrix.resolver-version }}
        ./latest $RESOLVER > stack-travis.yaml
        curl -L https://www.stackage.org/stack/linux-x86_64 | \
        tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
        stack update
        stack --no-terminal --skip-ghc-check setup
    - name: Debug info
      run: |
        echo $RESOLVER
        cat $STACK_YAML
    - name: Install deps
      run: |
        stack --no-terminal --skip-ghc-check test --only-snapshot
        # install jinja2
        pip3 install --user Jinja2
    - name: Build
      run: |
        stack --no-terminal --skip-ghc-check build
    - name: Test
      run: |
        stack --no-terminal --skip-ghc-check runghc example.hs
        stack --no-terminal --skip-ghc-check test --coverage
        cp -r $(stack path --local-hpc-root) hpc
    - name: Packaging
      run: |
        stack --no-terminal --skip-ghc-check sdist
    - uses: actions/upload-artifact@master
      with:
        name: coverage
        path: hpc
